title: Codeando
description: Un sitio de puro código.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

# add information for hacker page theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one